# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='pulication_date',
            new_name='publication_date',
        ),
    ]
