# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-28 16:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('publication_date', models.DateTimeField()),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('video_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='VideoFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='YoutubeFeed',
            fields=[
                ('videofeed_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clips.VideoFeed')),
                ('channel', models.CharField(max_length=200)),
                ('external_id', models.CharField(max_length=200)),
            ],
            bases=('clips.videofeed',),
        ),
        migrations.AddField(
            model_name='video',
            name='video_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.VideoFeed'),
        ),
    ]
