# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-29 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YoutubeVideo',
            fields=[
                ('video_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clips.Video')),
                ('embed_code', models.CharField(blank=True, max_length=200)),
            ],
            bases=('clips.video',),
        ),
    ]
