# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0002_youtubevideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubevideo',
            name='embed_code',
        ),
    ]
